name: time_chart
description: A scrollable time chart in Flutter. Currently supporting en, ko languages.
version: 0.1.0-nullsafety.1
homepage: https://github.com/jja08111/time_chart

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  linked_scroll_controller: ^0.2.0-nullsafety.0
  touchable: ^1.0.0-prerelease
  path_drawing: ^0.5.0-nullsafety.0
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter