name: time_chart
description: A scrollable time chart in Flutter. Currently supporting en, ko languages.
version: 0.0.5
homepage: https://github.com/jja08111/time_chart

environment:
  sdk: ">=2.5.2 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  linked_scroll_controller: ^0.1.2
  # Waiting for this PR: https://github.com/nateshmbhat/touchable/pull/17
  #touchable:
  #  git:
  #    url: https://github.com/jja08111/touchable
  path_drawing: ^0.4.1+1
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter